### ISSUE TITLE
Хранение БД в репозитории

### ISSUE THREAD

**Issue by dsokolov** [ViktoriaWofC/Diary#1]
По возможности стоит избегать хранения бинарников в репозитории. В частности вместо файла базы данных лучше хранить скрипты, создающие и наполняющие эту базу. Скрипты буду вызываться из кода и создавать базу на устройстве.

**Comment by ViktoriaWofC** [comment]
Убрала бинарник, добавила скрипт. У него годный формат?

**Comment by dsokolov** [comment]
Да, ок.
